services:
  - type: web
    name: ac-backend
    env: node
    plan: free
    rootDir: ./
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8000
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: FOLDER_NAME
        sync: false
      - key: RAZORPAY_KEY
        sync: false
      - key: RAZORPAY_SECRET
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false
